export const ROLES = {
  ADMIN: 'ADMIN',
  RESOURCE_MANAGER: 'RESOURCE_MANAGER',
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
  TEACHER: 'TEACHER',
  SUPPLIER: 'SUPPLIER',
  MAINTENANCE_TECHNICIAN: 'MAINTENANCE_TECHNICIAN',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

export const ALL_ROLES: readonly Role[] = Object.values(ROLES)

export const RESOURCE_TYPES = {
  COMPUTER: 'COMPUTER',
  PRINTER: 'PRINTER',
} as const
export type ResourceType = (typeof RESOURCE_TYPES)[keyof typeof RESOURCE_TYPES]

export const NEED_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_DEPARTMENT_REVIEW: 'UNDER_DEPARTMENT_REVIEW',
  CHANGES_REQUESTED: 'CHANGES_REQUESTED',
  APPROVED_BY_DEPARTMENT: 'APPROVED_BY_DEPARTMENT',
  SENT_TO_RESOURCE_MANAGER: 'SENT_TO_RESOURCE_MANAGER',
  INCLUDED_IN_TENDER: 'INCLUDED_IN_TENDER',
  REJECTED: 'REJECTED',
} as const
export type NeedStatus = (typeof NEED_STATUS)[keyof typeof NEED_STATUS]

export const TENDER_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  CLOSED: 'CLOSED',
  EVALUATION: 'EVALUATION',
  AWARDED: 'AWARDED',
  CANCELLED: 'CANCELLED',
} as const
export type TenderStatus = (typeof TENDER_STATUS)[keyof typeof TENDER_STATUS]

export const OFFER_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ELIMINATED: 'ELIMINATED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
} as const
export type OfferStatus = (typeof OFFER_STATUS)[keyof typeof OFFER_STATUS]

export const RESOURCE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  SENT_TO_SUPPLIER: 'SENT_TO_SUPPLIER',
  REPLACED: 'REPLACED',
  RETIRED: 'RETIRED',
  LOST: 'LOST',
} as const
export type ResourceStatus = (typeof RESOURCE_STATUS)[keyof typeof RESOURCE_STATUS]

export const FAILURE_STATUS = {
  REPORTED: 'REPORTED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  SEVERE: 'SEVERE',
  TECHNICAL_REPORT_CREATED: 'TECHNICAL_REPORT_CREATED',
  SENT_TO_SUPPLIER: 'SENT_TO_SUPPLIER',
} as const
export type FailureStatus = (typeof FAILURE_STATUS)[keyof typeof FAILURE_STATUS]

export const FAILURE_FREQUENCY = {
  RARE: 'RARE',
  FREQUENT: 'FREQUENT',
  PERMANENT: 'PERMANENT',
} as const
export type FailureFrequency = (typeof FAILURE_FREQUENCY)[keyof typeof FAILURE_FREQUENCY]

export const FAILURE_TYPE = {
  SOFTWARE_SYSTEM: 'SOFTWARE_SYSTEM',
  SOFTWARE_UTILITY: 'SOFTWARE_UTILITY',
  HARDWARE: 'HARDWARE',
} as const
export type FailureType = (typeof FAILURE_TYPE)[keyof typeof FAILURE_TYPE]

export const ASSIGNMENT_TARGET = {
  USER: 'USER',
  DEPARTMENT: 'DEPARTMENT',
} as const
export type AssignmentTarget = (typeof ASSIGNMENT_TARGET)[keyof typeof ASSIGNMENT_TARGET]

export const SUPPLIER_STATUS = {
  ACTIVE: 'ACTIVE',
  BLACKLISTED: 'BLACKLISTED',
  INACTIVE: 'INACTIVE',
} as const
export type SupplierStatus = (typeof SUPPLIER_STATUS)[keyof typeof SUPPLIER_STATUS]

export const NOTIFICATION_EVENT = {
  NEED_SUBMITTED: 'NEED_SUBMITTED',
  NEED_APPROVED: 'NEED_APPROVED',
  TENDER_PUBLISHED: 'TENDER_PUBLISHED',
  OFFER_SUBMITTED: 'OFFER_SUBMITTED',
  SUPPLIER_ELIMINATED: 'SUPPLIER_ELIMINATED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  RESOURCE_ASSIGNED: 'RESOURCE_ASSIGNED',
  FAILURE_REPORTED: 'FAILURE_REPORTED',
  TECHNICAL_REPORT_CREATED: 'TECHNICAL_REPORT_CREATED',
  SUPPLIER_REPAIR_REQUESTED: 'SUPPLIER_REPAIR_REQUESTED',
} as const
export type NotificationEvent =
  (typeof NOTIFICATION_EVENT)[keyof typeof NOTIFICATION_EVENT]

export const ERROR_CODES = {
  VALIDATION: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BUSINESS_RULE: 'BUSINESS_RULE_VIOLATION',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL_SERVER_ERROR',
} as const
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
