/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterSupplierRouteImport } from './routes/register-supplier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedSupplierIndexRouteImport } from './routes/_authenticated/supplier/index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager/index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance/index'
import { Route as AuthenticatedDepartmentIndexRouteImport } from './routes/_authenticated/department/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTeacherResourcesRouteImport } from './routes/_authenticated/teacher/resources'
import { Route as AuthenticatedTeacherNeedsRouteImport } from './routes/_authenticated/teacher/needs'
import { Route as AuthenticatedTeacherFailuresRouteImport } from './routes/_authenticated/teacher/failures'
import { Route as AuthenticatedSupplierTendersRouteImport } from './routes/_authenticated/supplier/tenders'
import { Route as AuthenticatedSupplierProfileRouteImport } from './routes/_authenticated/supplier/profile'
import { Route as AuthenticatedSupplierOffersRouteImport } from './routes/_authenticated/supplier/offers'
import { Route as AuthenticatedManagerTendersRouteImport } from './routes/_authenticated/manager/tenders'
import { Route as AuthenticatedManagerSuppliersRouteImport } from './routes/_authenticated/manager/suppliers'
import { Route as AuthenticatedManagerResourcesRouteImport } from './routes/_authenticated/manager/resources'
import { Route as AuthenticatedManagerMaintenanceDecisionsRouteImport } from './routes/_authenticated/manager/maintenance-decisions'
import { Route as AuthenticatedMaintenanceReportsRouteImport } from './routes/_authenticated/maintenance/reports'
import { Route as AuthenticatedMaintenanceFailuresRouteImport } from './routes/_authenticated/maintenance/failures'
import { Route as AuthenticatedDepartmentResourcesRouteImport } from './routes/_authenticated/department/resources'
import { Route as AuthenticatedDepartmentNeedsRouteImport } from './routes/_authenticated/department/needs'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin/departments'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedSupplierTendersTenderIdSubmitOfferRouteImport } from './routes/_authenticated/supplier/tenders.$tenderId.submit-offer'
import { Route as AuthenticatedManagerTendersTenderIdEvaluationRouteImport } from './routes/_authenticated/manager/tenders.$tenderId.evaluation'
import { Route as AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRouteImport } from './routes/_authenticated/maintenance/failures.$failureId.technical-report'

const RegisterSupplierRoute = RegisterSupplierRouteImport.update({
  id: '/register-supplier',
  path: '/register-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierIndexRoute =
  AuthenticatedSupplierIndexRouteImport.update({
    id: '/supplier/',
    path: '/supplier/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepartmentIndexRoute =
  AuthenticatedDepartmentIndexRouteImport.update({
    id: '/department/',
    path: '/department/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherResourcesRoute =
  AuthenticatedTeacherResourcesRouteImport.update({
    id: '/teacher/resources',
    path: '/teacher/resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherNeedsRoute =
  AuthenticatedTeacherNeedsRouteImport.update({
    id: '/teacher/needs',
    path: '/teacher/needs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherFailuresRoute =
  AuthenticatedTeacherFailuresRouteImport.update({
    id: '/teacher/failures',
    path: '/teacher/failures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierTendersRoute =
  AuthenticatedSupplierTendersRouteImport.update({
    id: '/supplier/tenders',
    path: '/supplier/tenders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierProfileRoute =
  AuthenticatedSupplierProfileRouteImport.update({
    id: '/supplier/profile',
    path: '/supplier/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierOffersRoute =
  AuthenticatedSupplierOffersRouteImport.update({
    id: '/supplier/offers',
    path: '/supplier/offers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTendersRoute =
  AuthenticatedManagerTendersRouteImport.update({
    id: '/manager/tenders',
    path: '/manager/tenders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerSuppliersRoute =
  AuthenticatedManagerSuppliersRouteImport.update({
    id: '/manager/suppliers',
    path: '/manager/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerResourcesRoute =
  AuthenticatedManagerResourcesRouteImport.update({
    id: '/manager/resources',
    path: '/manager/resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerMaintenanceDecisionsRoute =
  AuthenticatedManagerMaintenanceDecisionsRouteImport.update({
    id: '/manager/maintenance-decisions',
    path: '/manager/maintenance-decisions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceReportsRoute =
  AuthenticatedMaintenanceReportsRouteImport.update({
    id: '/maintenance/reports',
    path: '/maintenance/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceFailuresRoute =
  AuthenticatedMaintenanceFailuresRouteImport.update({
    id: '/maintenance/failures',
    path: '/maintenance/failures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepartmentResourcesRoute =
  AuthenticatedDepartmentResourcesRouteImport.update({
    id: '/department/resources',
    path: '/department/resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepartmentNeedsRoute =
  AuthenticatedDepartmentNeedsRouteImport.update({
    id: '/department/needs',
    path: '/department/needs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierTendersTenderIdSubmitOfferRoute =
  AuthenticatedSupplierTendersTenderIdSubmitOfferRouteImport.update({
    id: '/$tenderId/submit-offer',
    path: '/$tenderId/submit-offer',
    getParentRoute: () => AuthenticatedSupplierTendersRoute,
  } as any)
const AuthenticatedManagerTendersTenderIdEvaluationRoute =
  AuthenticatedManagerTendersTenderIdEvaluationRouteImport.update({
    id: '/$tenderId/evaluation',
    path: '/$tenderId/evaluation',
    getParentRoute: () => AuthenticatedManagerTendersRoute,
  } as any)
const AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute =
  AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRouteImport.update({
    id: '/$failureId/technical-report',
    path: '/$failureId/technical-report',
    getParentRoute: () => AuthenticatedMaintenanceFailuresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-supplier': typeof RegisterSupplierRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/department/needs': typeof AuthenticatedDepartmentNeedsRoute
  '/department/resources': typeof AuthenticatedDepartmentResourcesRoute
  '/maintenance/failures': typeof AuthenticatedMaintenanceFailuresRouteWithChildren
  '/maintenance/reports': typeof AuthenticatedMaintenanceReportsRoute
  '/manager/maintenance-decisions': typeof AuthenticatedManagerMaintenanceDecisionsRoute
  '/manager/resources': typeof AuthenticatedManagerResourcesRoute
  '/manager/suppliers': typeof AuthenticatedManagerSuppliersRoute
  '/manager/tenders': typeof AuthenticatedManagerTendersRouteWithChildren
  '/supplier/offers': typeof AuthenticatedSupplierOffersRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/tenders': typeof AuthenticatedSupplierTendersRouteWithChildren
  '/teacher/failures': typeof AuthenticatedTeacherFailuresRoute
  '/teacher/needs': typeof AuthenticatedTeacherNeedsRoute
  '/teacher/resources': typeof AuthenticatedTeacherResourcesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/department/': typeof AuthenticatedDepartmentIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/maintenance/failures/$failureId/technical-report': typeof AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute
  '/manager/tenders/$tenderId/evaluation': typeof AuthenticatedManagerTendersTenderIdEvaluationRoute
  '/supplier/tenders/$tenderId/submit-offer': typeof AuthenticatedSupplierTendersTenderIdSubmitOfferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-supplier': typeof RegisterSupplierRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/department/needs': typeof AuthenticatedDepartmentNeedsRoute
  '/department/resources': typeof AuthenticatedDepartmentResourcesRoute
  '/maintenance/failures': typeof AuthenticatedMaintenanceFailuresRouteWithChildren
  '/maintenance/reports': typeof AuthenticatedMaintenanceReportsRoute
  '/manager/maintenance-decisions': typeof AuthenticatedManagerMaintenanceDecisionsRoute
  '/manager/resources': typeof AuthenticatedManagerResourcesRoute
  '/manager/suppliers': typeof AuthenticatedManagerSuppliersRoute
  '/manager/tenders': typeof AuthenticatedManagerTendersRouteWithChildren
  '/supplier/offers': typeof AuthenticatedSupplierOffersRoute
  '/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/supplier/tenders': typeof AuthenticatedSupplierTendersRouteWithChildren
  '/teacher/failures': typeof AuthenticatedTeacherFailuresRoute
  '/teacher/needs': typeof AuthenticatedTeacherNeedsRoute
  '/teacher/resources': typeof AuthenticatedTeacherResourcesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/department': typeof AuthenticatedDepartmentIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/supplier': typeof AuthenticatedSupplierIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/maintenance/failures/$failureId/technical-report': typeof AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute
  '/manager/tenders/$tenderId/evaluation': typeof AuthenticatedManagerTendersTenderIdEvaluationRoute
  '/supplier/tenders/$tenderId/submit-offer': typeof AuthenticatedSupplierTendersTenderIdSubmitOfferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register-supplier': typeof RegisterSupplierRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/department/needs': typeof AuthenticatedDepartmentNeedsRoute
  '/_authenticated/department/resources': typeof AuthenticatedDepartmentResourcesRoute
  '/_authenticated/maintenance/failures': typeof AuthenticatedMaintenanceFailuresRouteWithChildren
  '/_authenticated/maintenance/reports': typeof AuthenticatedMaintenanceReportsRoute
  '/_authenticated/manager/maintenance-decisions': typeof AuthenticatedManagerMaintenanceDecisionsRoute
  '/_authenticated/manager/resources': typeof AuthenticatedManagerResourcesRoute
  '/_authenticated/manager/suppliers': typeof AuthenticatedManagerSuppliersRoute
  '/_authenticated/manager/tenders': typeof AuthenticatedManagerTendersRouteWithChildren
  '/_authenticated/supplier/offers': typeof AuthenticatedSupplierOffersRoute
  '/_authenticated/supplier/profile': typeof AuthenticatedSupplierProfileRoute
  '/_authenticated/supplier/tenders': typeof AuthenticatedSupplierTendersRouteWithChildren
  '/_authenticated/teacher/failures': typeof AuthenticatedTeacherFailuresRoute
  '/_authenticated/teacher/needs': typeof AuthenticatedTeacherNeedsRoute
  '/_authenticated/teacher/resources': typeof AuthenticatedTeacherResourcesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/department/': typeof AuthenticatedDepartmentIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/maintenance/failures/$failureId/technical-report': typeof AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute
  '/_authenticated/manager/tenders/$tenderId/evaluation': typeof AuthenticatedManagerTendersTenderIdEvaluationRoute
  '/_authenticated/supplier/tenders/$tenderId/submit-offer': typeof AuthenticatedSupplierTendersTenderIdSubmitOfferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register-supplier'
    | '/dashboard'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/users'
    | '/department/needs'
    | '/department/resources'
    | '/maintenance/failures'
    | '/maintenance/reports'
    | '/manager/maintenance-decisions'
    | '/manager/resources'
    | '/manager/suppliers'
    | '/manager/tenders'
    | '/supplier/offers'
    | '/supplier/profile'
    | '/supplier/tenders'
    | '/teacher/failures'
    | '/teacher/needs'
    | '/teacher/resources'
    | '/admin/'
    | '/department/'
    | '/maintenance/'
    | '/manager/'
    | '/supplier/'
    | '/teacher/'
    | '/maintenance/failures/$failureId/technical-report'
    | '/manager/tenders/$tenderId/evaluation'
    | '/supplier/tenders/$tenderId/submit-offer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register-supplier'
    | '/dashboard'
    | '/admin/audit-logs'
    | '/admin/departments'
    | '/admin/users'
    | '/department/needs'
    | '/department/resources'
    | '/maintenance/failures'
    | '/maintenance/reports'
    | '/manager/maintenance-decisions'
    | '/manager/resources'
    | '/manager/suppliers'
    | '/manager/tenders'
    | '/supplier/offers'
    | '/supplier/profile'
    | '/supplier/tenders'
    | '/teacher/failures'
    | '/teacher/needs'
    | '/teacher/resources'
    | '/admin'
    | '/department'
    | '/maintenance'
    | '/manager'
    | '/supplier'
    | '/teacher'
    | '/maintenance/failures/$failureId/technical-report'
    | '/manager/tenders/$tenderId/evaluation'
    | '/supplier/tenders/$tenderId/submit-offer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register-supplier'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/users'
    | '/_authenticated/department/needs'
    | '/_authenticated/department/resources'
    | '/_authenticated/maintenance/failures'
    | '/_authenticated/maintenance/reports'
    | '/_authenticated/manager/maintenance-decisions'
    | '/_authenticated/manager/resources'
    | '/_authenticated/manager/suppliers'
    | '/_authenticated/manager/tenders'
    | '/_authenticated/supplier/offers'
    | '/_authenticated/supplier/profile'
    | '/_authenticated/supplier/tenders'
    | '/_authenticated/teacher/failures'
    | '/_authenticated/teacher/needs'
    | '/_authenticated/teacher/resources'
    | '/_authenticated/admin/'
    | '/_authenticated/department/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/manager/'
    | '/_authenticated/supplier/'
    | '/_authenticated/teacher/'
    | '/_authenticated/maintenance/failures/$failureId/technical-report'
    | '/_authenticated/manager/tenders/$tenderId/evaluation'
    | '/_authenticated/supplier/tenders/$tenderId/submit-offer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterSupplierRoute: typeof RegisterSupplierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-supplier': {
      id: '/register-supplier'
      path: '/register-supplier'
      fullPath: '/register-supplier'
      preLoaderRoute: typeof RegisterSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/': {
      id: '/_authenticated/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AuthenticatedSupplierIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/department/': {
      id: '/_authenticated/department/'
      path: '/department'
      fullPath: '/department/'
      preLoaderRoute: typeof AuthenticatedDepartmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/resources': {
      id: '/_authenticated/teacher/resources'
      path: '/teacher/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof AuthenticatedTeacherResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/needs': {
      id: '/_authenticated/teacher/needs'
      path: '/teacher/needs'
      fullPath: '/teacher/needs'
      preLoaderRoute: typeof AuthenticatedTeacherNeedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/failures': {
      id: '/_authenticated/teacher/failures'
      path: '/teacher/failures'
      fullPath: '/teacher/failures'
      preLoaderRoute: typeof AuthenticatedTeacherFailuresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/tenders': {
      id: '/_authenticated/supplier/tenders'
      path: '/supplier/tenders'
      fullPath: '/supplier/tenders'
      preLoaderRoute: typeof AuthenticatedSupplierTendersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/profile': {
      id: '/_authenticated/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof AuthenticatedSupplierProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/offers': {
      id: '/_authenticated/supplier/offers'
      path: '/supplier/offers'
      fullPath: '/supplier/offers'
      preLoaderRoute: typeof AuthenticatedSupplierOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/tenders': {
      id: '/_authenticated/manager/tenders'
      path: '/manager/tenders'
      fullPath: '/manager/tenders'
      preLoaderRoute: typeof AuthenticatedManagerTendersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/suppliers': {
      id: '/_authenticated/manager/suppliers'
      path: '/manager/suppliers'
      fullPath: '/manager/suppliers'
      preLoaderRoute: typeof AuthenticatedManagerSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/resources': {
      id: '/_authenticated/manager/resources'
      path: '/manager/resources'
      fullPath: '/manager/resources'
      preLoaderRoute: typeof AuthenticatedManagerResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/maintenance-decisions': {
      id: '/_authenticated/manager/maintenance-decisions'
      path: '/manager/maintenance-decisions'
      fullPath: '/manager/maintenance-decisions'
      preLoaderRoute: typeof AuthenticatedManagerMaintenanceDecisionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/reports': {
      id: '/_authenticated/maintenance/reports'
      path: '/maintenance/reports'
      fullPath: '/maintenance/reports'
      preLoaderRoute: typeof AuthenticatedMaintenanceReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/failures': {
      id: '/_authenticated/maintenance/failures'
      path: '/maintenance/failures'
      fullPath: '/maintenance/failures'
      preLoaderRoute: typeof AuthenticatedMaintenanceFailuresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/department/resources': {
      id: '/_authenticated/department/resources'
      path: '/department/resources'
      fullPath: '/department/resources'
      preLoaderRoute: typeof AuthenticatedDepartmentResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/department/needs': {
      id: '/_authenticated/department/needs'
      path: '/department/needs'
      fullPath: '/department/needs'
      preLoaderRoute: typeof AuthenticatedDepartmentNeedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/tenders/$tenderId/submit-offer': {
      id: '/_authenticated/supplier/tenders/$tenderId/submit-offer'
      path: '/$tenderId/submit-offer'
      fullPath: '/supplier/tenders/$tenderId/submit-offer'
      preLoaderRoute: typeof AuthenticatedSupplierTendersTenderIdSubmitOfferRouteImport
      parentRoute: typeof AuthenticatedSupplierTendersRoute
    }
    '/_authenticated/manager/tenders/$tenderId/evaluation': {
      id: '/_authenticated/manager/tenders/$tenderId/evaluation'
      path: '/$tenderId/evaluation'
      fullPath: '/manager/tenders/$tenderId/evaluation'
      preLoaderRoute: typeof AuthenticatedManagerTendersTenderIdEvaluationRouteImport
      parentRoute: typeof AuthenticatedManagerTendersRoute
    }
    '/_authenticated/maintenance/failures/$failureId/technical-report': {
      id: '/_authenticated/maintenance/failures/$failureId/technical-report'
      path: '/$failureId/technical-report'
      fullPath: '/maintenance/failures/$failureId/technical-report'
      preLoaderRoute: typeof AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRouteImport
      parentRoute: typeof AuthenticatedMaintenanceFailuresRoute
    }
  }
}

interface AuthenticatedMaintenanceFailuresRouteChildren {
  AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute: typeof AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute
}

const AuthenticatedMaintenanceFailuresRouteChildren: AuthenticatedMaintenanceFailuresRouteChildren =
  {
    AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute:
      AuthenticatedMaintenanceFailuresFailureIdTechnicalReportRoute,
  }

const AuthenticatedMaintenanceFailuresRouteWithChildren =
  AuthenticatedMaintenanceFailuresRoute._addFileChildren(
    AuthenticatedMaintenanceFailuresRouteChildren,
  )

interface AuthenticatedManagerTendersRouteChildren {
  AuthenticatedManagerTendersTenderIdEvaluationRoute: typeof AuthenticatedManagerTendersTenderIdEvaluationRoute
}

const AuthenticatedManagerTendersRouteChildren: AuthenticatedManagerTendersRouteChildren =
  {
    AuthenticatedManagerTendersTenderIdEvaluationRoute:
      AuthenticatedManagerTendersTenderIdEvaluationRoute,
  }

const AuthenticatedManagerTendersRouteWithChildren =
  AuthenticatedManagerTendersRoute._addFileChildren(
    AuthenticatedManagerTendersRouteChildren,
  )

interface AuthenticatedSupplierTendersRouteChildren {
  AuthenticatedSupplierTendersTenderIdSubmitOfferRoute: typeof AuthenticatedSupplierTendersTenderIdSubmitOfferRoute
}

const AuthenticatedSupplierTendersRouteChildren: AuthenticatedSupplierTendersRouteChildren =
  {
    AuthenticatedSupplierTendersTenderIdSubmitOfferRoute:
      AuthenticatedSupplierTendersTenderIdSubmitOfferRoute,
  }

const AuthenticatedSupplierTendersRouteWithChildren =
  AuthenticatedSupplierTendersRoute._addFileChildren(
    AuthenticatedSupplierTendersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDepartmentNeedsRoute: typeof AuthenticatedDepartmentNeedsRoute
  AuthenticatedDepartmentResourcesRoute: typeof AuthenticatedDepartmentResourcesRoute
  AuthenticatedMaintenanceFailuresRoute: typeof AuthenticatedMaintenanceFailuresRouteWithChildren
  AuthenticatedMaintenanceReportsRoute: typeof AuthenticatedMaintenanceReportsRoute
  AuthenticatedManagerMaintenanceDecisionsRoute: typeof AuthenticatedManagerMaintenanceDecisionsRoute
  AuthenticatedManagerResourcesRoute: typeof AuthenticatedManagerResourcesRoute
  AuthenticatedManagerSuppliersRoute: typeof AuthenticatedManagerSuppliersRoute
  AuthenticatedManagerTendersRoute: typeof AuthenticatedManagerTendersRouteWithChildren
  AuthenticatedSupplierOffersRoute: typeof AuthenticatedSupplierOffersRoute
  AuthenticatedSupplierProfileRoute: typeof AuthenticatedSupplierProfileRoute
  AuthenticatedSupplierTendersRoute: typeof AuthenticatedSupplierTendersRouteWithChildren
  AuthenticatedTeacherFailuresRoute: typeof AuthenticatedTeacherFailuresRoute
  AuthenticatedTeacherNeedsRoute: typeof AuthenticatedTeacherNeedsRoute
  AuthenticatedTeacherResourcesRoute: typeof AuthenticatedTeacherResourcesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDepartmentIndexRoute: typeof AuthenticatedDepartmentIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedSupplierIndexRoute: typeof AuthenticatedSupplierIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDepartmentNeedsRoute: AuthenticatedDepartmentNeedsRoute,
  AuthenticatedDepartmentResourcesRoute: AuthenticatedDepartmentResourcesRoute,
  AuthenticatedMaintenanceFailuresRoute:
    AuthenticatedMaintenanceFailuresRouteWithChildren,
  AuthenticatedMaintenanceReportsRoute: AuthenticatedMaintenanceReportsRoute,
  AuthenticatedManagerMaintenanceDecisionsRoute:
    AuthenticatedManagerMaintenanceDecisionsRoute,
  AuthenticatedManagerResourcesRoute: AuthenticatedManagerResourcesRoute,
  AuthenticatedManagerSuppliersRoute: AuthenticatedManagerSuppliersRoute,
  AuthenticatedManagerTendersRoute:
    AuthenticatedManagerTendersRouteWithChildren,
  AuthenticatedSupplierOffersRoute: AuthenticatedSupplierOffersRoute,
  AuthenticatedSupplierProfileRoute: AuthenticatedSupplierProfileRoute,
  AuthenticatedSupplierTendersRoute:
    AuthenticatedSupplierTendersRouteWithChildren,
  AuthenticatedTeacherFailuresRoute: AuthenticatedTeacherFailuresRoute,
  AuthenticatedTeacherNeedsRoute: AuthenticatedTeacherNeedsRoute,
  AuthenticatedTeacherResourcesRoute: AuthenticatedTeacherResourcesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDepartmentIndexRoute: AuthenticatedDepartmentIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedSupplierIndexRoute: AuthenticatedSupplierIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterSupplierRoute: RegisterSupplierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
